export const productData = [
  {
    pageUrl: "SIMVASTATIN-TABlets-USP",
    productName: "rohit TABlets USP 20mg rkm",
    brandName: "imvast 200",
    batchCode: "MET25001",
    manufactureDate: "Jan 2025",
    expiryDate: "Dec 2027",
    images: ["https://picsum.photos/id/237/200/300"],
    description: {
      genericName: "Born Supplement",
      composition: "B1, B2, Vitamins, and Minerals",
      storePoint: "Store in a cool, dry place away from sunlight",
      Dosage: "One gummy daily",
      exportedBy: "JUMI Exports",
      importedBy: "JUMI Imports",
      manufacturedBy: "JUMI Manufacturing",
    },
  },
  {
    pageUrl: "ATORVASTATIN-CAPSULES-10MG",
    productName: "neeraj Capsules USP 10mg nk",
    brandName: "cholstat 10",
    batchCode: "ATO12345",
    manufactureDate: "Feb 2024",
    expiryDate: "Jan 2026",
    images: ["https://picsum.photos/id/238/200/300"],
    description: {
      genericName: "Lipid Lowering Agent",
      composition: "Atorvastatin Calcium",
      storePoint: "Store in a cool, dry place below 25°C",
      Dosage: "One capsule daily as prescribed",
      exportedBy: "PharmaLife Exports",
      importedBy: "PharmaLife Imports",
      manufacturedBy: "PharmaLife Manufacturing",
    },
  },
  {
    pageUrl: "OMEPRAZOLE-ORAL-SUSPENSION-10MG",
    productName: "pranav Suspension USP 10mg cp",
    brandName: "omepradex 10",
    batchCode: "OMP67890",
    manufactureDate: "Mar 2023",
    expiryDate: "Feb 2025",
    images: ["https://picsum.photos/id/239/200/300"],
    description: {
      genericName: "Proton Pump Inhibitor",
      composition: "Omeprazole",
      storePoint: "Store at room temperature, away from light",
      Dosage: "Take one teaspoon daily",
      exportedBy: "HealEx Exports",
      importedBy: "HealEx Imports",
      manufacturedBy: "HealEx Manufacturing",
    },
  },
  {
    pageUrl: "DIAZEPAM-TABLETS-5MG",
    productName: "krishna Tablets USP 5mg dp",
    brandName: "relaxol 5",
    batchCode: "DIA11234",
    manufactureDate: "Oct 2023",
    expiryDate: "Sep 2026",
    images: ["https://picsum.photos/id/240/200/300"],
    description: {
      genericName: "Anxiolytic",
      composition: "Diazepam",
      storePoint: "Store in a cool, dry place away from heat",
      Dosage: "One tablet daily or as prescribed",
      exportedBy: "Serene Exports",
      importedBy: "Serene Imports",
      manufacturedBy: "Serene Manufacturing",
    },
  },
  {
    pageUrl: "AMOXICILLIN-CAPSULES-500MG",
    productName: "ashok Capsules USP 500mg amx",
    brandName: "amoxic 500",
    batchCode: "AMO87654",
    manufactureDate: "Dec 2023",
    expiryDate: "Nov 2026",
    images: ["https://picsum.photos/id/241/200/300"],
    description: {
      genericName: "Antibiotic",
      composition: "Amoxicillin",
      storePoint: "Store below 30°C, away from moisture",
      Dosage: "Take one capsule every 8 hours",
      exportedBy: "MediWorld Exports",
      importedBy: "MediWorld Imports",
      manufacturedBy: "MediWorld Manufacturing",
    },
  },
];
