export const tabletData = [
  { productName: "Capecitabine Tablets USP", strengths: "150 mg" },
  { productName: "Capecitabine Tablets USP", strengths: "500 mg" },
  { productName: "Gefitinib Tablets", strengths: "250 mg" },
  { productName: "Erlotinib Tablets", strengths: "100 mg" },
  { productName: "Erlotinib Tablets", strengths: "150 mg" },
  { productName: "Anastrozole Tablets", strengths: "1.0 mg" },
  { productName: "Imatinib Tablets", strengths: "100 mg" },
  { productName: "Imatinib Tablets", strengths: "400 mg" },
  { productName: "Methotrexate Tablets BP", strengths: "2.5 mg" },
  { productName: "Methotrexate Tablets BP", strengths: "7.5 mg" },
  { productName: "Methotrexate Tablets BP", strengths: "15 mg" },
  { productName: "Everolimus Tablets", strengths: "5.0 mg" },
  { productName: "Everolimus Tablets", strengths: "10 mg" },
  {
    productName: "Abiraterone Acetate Tablets USP",
    strengths: "250 mg",
  },
  {
    productName: "Abiraterone Acetate Tablets USP",
    strengths: "500 mg",
  },
  { productName: "Lapatinib Tablets", strengths: "250 mg" },
  { productName: "Sorafenib Tablets", strengths: "250 mg" },
  { productName: "Letrozole Tablets USP", strengths: "2.5 mg" },
  { productName: "Tamoxifen Tablets BP", strengths: "10 mg" },
  { productName: "Tamoxifen Tablets BP", strengths: "20 mg" },
  { productName: "Tamoxifen Tablets BP", strengths: "40 mg" },
  { productName: "Mercaptopurine Tablets BP", strengths: "50 mg" },
  { productName: "Dasatinib Tablets", strengths: "50 mg" },
  { productName: "Dasatinib Tablets", strengths: "70 mg" },
  { productName: "Dasatinib Tablets", strengths: "100 mg" },
  { productName: "Nilutamide Tablets", strengths: "150 mg" },
  { productName: "Letrozole Tablet USP", strengths: "2.5 mg" },
  { productName: "Flutamide Tablet", strengths: "250 mg" },
  { productName: "Exemestane Tablet", strengths: "25 mg" },
  { productName: "Fludarabine Phosphate Tablet", strengths: "10 mg" },
  { productName: "Melphalan Tablets BP", strengths: "2.0 mg" },
  { productName: "Melphalan Tablets BP", strengths: "4.0 mg" },
  { productName: "Mitotane Tablet USP", strengths: "500 mg" },
  { productName: "Megestrol Acetate Tablet USP", strengths: "40 mg" },
  { productName: "Megestrol Acetate Tablet USP", strengths: "160 mg" },
  { productName: "Axitinib Tablet", strengths: "1.0 mg" },
  { productName: "Axitinib Tablet", strengths: "5.0 mg" },
  { productName: "Pazopanib Tablet", strengths: "200 mg" },
  { productName: "Pazopanib Tablet", strengths: "400 mg" },
  { productName: "Valganciclovir Tablets USP", strengths: "450 mg" },
  { productName: "Deferasirox Tablets", strengths: "125 mg" },
  { productName: "Deferasirox Tablets", strengths: "250 mg" },
  { productName: "Deferasirox Tablets", strengths: "500 mg" },
  { productName: "Regorafenib Tablets", strengths: "40 mg" },
  { productName: "Osimertinib Tablets", strengths: "40 mg" },
  { productName: "Osimertinib Tablets", strengths: "80 mg" },
  {
    productName: "Mycophenolate Mofetil Tablets USP",
    strengths: "500 mg",
  },
];

export const capsuleData = [
  { productName: "Etoposide Capsules USP", strengths: "50 mg" },
  { productName: "Etoposide Capsules USP", strengths: "100 mg" },
  { productName: "Thalidomide Capsules USP", strengths: "50 mg" },
  { productName: "Thalidomide Capsules USP", strengths: "100 mg" },
  { productName: "Thalidomide Capsules USP", strengths: "200 mg" },
  { productName: "Temozolomide Capsules", strengths: "100 mg" },
  { productName: "Imatinib Capsules", strengths: "" }, // No strengths provided
  { productName: "Lenalidomide Capsules", strengths: "5.0 mg" },
  { productName: "Lenalidomide Capsules", strengths: "10 mg" },
  { productName: "Lenalidomide Capsules", strengths: "15 mg" },
  { productName: "Lenalidomide Capsules", strengths: "25 mg" },
  { productName: "Sunitinib Malate Capsules", strengths: "12.5 mg" },
  { productName: "Sunitinib Malate Capsules", strengths: "25 mg" },
  { productName: "Sunitinib Malate Capsules", strengths: "50 mg" },
  { productName: "Ganciclovir Capsules USP", strengths: "250 mg" },
  { productName: "Ganciclovir Capsules USP", strengths: "500 mg" },
  { productName: "Crizotinib Capsules", strengths: "200 mg" },
  { productName: "Crizotinib Capsules", strengths: "250 mg" },
  { productName: "Tacrolimus Capsules USP", strengths: "0.5 mg" },
  {
    productName: "Tacrolimus Capsules USP 0.5/1.0 mg",
    strengths: "1.0 mg",
  },
  { productName: "Nilotinib Capsules", strengths: "200 mg" },
  { productName: "Palbociclib Capsules", strengths: "75 mg" },
  { productName: "Palbociclib Capsules", strengths: "100 mg" },
  { productName: "Palbociclib Capsules", strengths: "125 mg" },
  { productName: "Aprepitant Capsules BP", strengths: "80/125 mg" },
  { productName: "Ibrutinib Capsules", strengths: "140 mg" },
  { productName: "Hydroxyurea Capsules USP", strengths: "500 mg" },
  {
    productName: "Procarbazine Hydrochloride Capsules USP",
    strengths: "50 mg",
  },
  { productName: "Enzalutamide Capsules", strengths: "40 mg" },
  { productName: "Danazol Capsules USP", strengths: "200 mg" },
  { productName: "Tretinoin Capsules", strengths: "10 mg" },
  { productName: "Lenvatinib Capsules", strengths: "4.0 mg" },
  { productName: "Lenvatinib Capsules", strengths: "10 mg" },
];

export const oncoInjections = [
  {
    productName: "Amifostine For Injection USP",
    strengths: "500 mg (As Lyophilized)",
  },
  {
    productName: "Amphotericin B For Injection USP",
    strengths: "50 mg (As Lyophilized)",
  },
  { productName: "Amphotericin B Liposomal Injection", strengths: "50 mg" },
  { productName: "Arsenic Trioxide Injection", strengths: "1.0 mg/ml" },
  { productName: "Azacitadine Injection", strengths: "200 mg" },
  {
    productName: "Azacitidine For Injection",
    strengths: "100 mg / Vial (As Lyophilized)",
  },
  {
    productName: "Bendamustin For Injection",
    strengths: "100 mg/vial (As Lyophilized)",
  },
  {
    productName: "Bleomycin Sulfate For Injection IP",
    strengths: "15 IU/ vial (As Lyophilized)",
  },
  {
    productName: "Bortezomib For Injection",
    strengths: "2.0 mg/vial (As Lyophilized)",
  },
  {
    productName: "Bortezomib For Injection",
    strengths: "3.5 mg/vial (As Lyophilized)",
  },
  { productName: "Busulfan Injection", strengths: "60 mg/10 ml" },
  { productName: "Cabazitaxel Injection", strengths: "60 mg/1.5 ml" },
  {
    productName: "Carboplatin For Injection",
    strengths: "50 mg (As Lyophilized)",
  },
  {
    productName: "Carboplatin For Injection",
    strengths: "150 mg (As Lyophilized)",
  },
  {
    productName: "Carboplatin For Injection",
    strengths: "450 mg (As Lyophilized)",
  },
  { productName: "Carboplatin Injection BP", strengths: "450 mg/45 ml" },
  { productName: "Carboplatin Injection BP", strengths: "150 mg/15 ml" },
  {
    productName: "Carmustine For Injection USP",
    strengths: "100 mg/vial (As Lyophilized)",
  },
  { productName: "Cisplatin Injection BP", strengths: "10 mg/20 ml" },
  { productName: "Cisplatin Injection BP", strengths: "10 mg/10 ml" },
  { productName: "Cisplatin Injection BP", strengths: "50 mg/50 ml" },
  {
    productName: "Cisplatin Liposomal Injection",
    strengths: "150 mg/50 ml (As Nanoparticle Suspension)",
  },
  {
    productName: "Cyclophosphamide Injection BP",
    strengths: "200 mg/vial (As Lyophilized)",
  },
  {
    productName: "Cyclophosphamide Injection BP",
    strengths: "500 mg/vial (As Lyophilized)",
  },
  {
    productName: "Cyclophosphamide Injection BP",
    strengths: "1000 mg/vial (As Lyophilized)",
  },
  { productName: "Cytarabine Injection BP", strengths: "100 mg/ml" },
  { productName: "Cytarabine Injection BP", strengths: "500 mg/5 ml" },
  { productName: "Cytarabine Injection BP", strengths: "1000 mg/10 ml" },
  {
    productName: "Dacarbazine For Injection BP",
    strengths: "200 mg/vial (As Lyophilized)",
  },
  {
    productName: "Dacarbazine For Injection BP",
    strengths: "500 mg/vial (As Lyophilized)",
  },
  { productName: "Dactinomycin Injection", strengths: "0.5 mg" },
  {
    productName: "Daunorubicin For Injection USP",
    strengths: "20 mg/vial (As Lyophilized)",
  },
  {
    productName: "Daunorubicin Injection",
    strengths: "50 mg/25 ml (As Liposomal)",
  },
  {
    productName: "Decitabine For Injection",
    strengths: "50 mg/vial (As Lyophilized)",
  },
  {
    productName: "Degarelix For Injection",
    strengths: "120 mg (As Lyophilized)",
  },
  {
    productName: "Degarelix For Injection",
    strengths: "80 mg (As Lyophilized)",
  },
  {
    productName: "Diluent For Cabazitaxel Injection",
    strengths: "60 mg/1.5 ml",
  },
  { productName: "Docetaxel Injection USP", strengths: "20 mg/0.5 ml" },
  { productName: "Docetaxel Injection USP", strengths: "80 mg/2.0 ml" },
  { productName: "Docetaxel Injection USP", strengths: "120 mg/3.0 ml" },
  { productName: "Docetaxel Injection USP", strengths: "80 mg/8 ml RTU" },
  { productName: "Docetaxel Injection USP", strengths: "20 mg/2.0 ml RTU" },
  {
    productName: "Doxorubicin Hydrochloride For Injection BP",
    strengths: "10/50 mg/vial (As Lyophilized)",
  },
  {
    productName: "Doxorubicin Hydrochloride Liposome Injection",
    strengths: "20 mg/10 ml",
  },
  {
    productName: "Doxorubicin Hydrochloride Liposome Injection",
    strengths: "10 mg/5 ml (As Pegylated Liposome)",
  },
  {
    productName: "Doxorubicin Injection",
    strengths: "10 mg/10 ml (As Liposomal)",
  },
  {
    productName: "Doxorubicin Injection",
    strengths: "20 mg/20 ml (As Liposomal)",
  },
  { productName: "Doxorubicin Injection BP", strengths: "10 mg/5 ml" },
  { productName: "Doxorubicin Injection BP", strengths: "50 mg/25 ml" },
  {
    productName: "Epirubicin Hydrochloride For Injection",
    strengths: "100 mg/vial (As Lyophilized)",
  },
  { productName: "Epirubicin Injection BP", strengths: "10 mg/5 ml" },
  { productName: "Epirubicin Injection BP", strengths: "50 mg/25 ml" },
  {
    productName: "Eribulin Mesylate Solution For Injection",
    strengths: "0.88 mg/2 ml",
  },
  { productName: "Etoposide Injection USP", strengths: "100 mg/5 ml" },
  { productName: "Etoposide Injection USP", strengths: "250 mg/12.5 ml" },
  { productName: "Etoposide Injection USP", strengths: "500 mg/25 ml" },
  { productName: "Etoposide Injection USP", strengths: "1000 mg/50 ml" },
  { productName: "Filgrastim Injection Solution", strengths: "300 mcg/ml" },
  {
    productName: "Fludarabine Phosphate For Injection USP",
    strengths: "50 mg/vial (As Lyophilized)",
  },
  { productName: "Fluorouracil Injection BP", strengths: "250 mg/10 ml/5 ml" },
  { productName: "Fosaprepitant Injection", strengths: "150 mg" },
  { productName: "Fulvestrant Injection", strengths: "250 mg/5 ml" },
  {
    productName: "Ganciclovir For Injection USP",
    strengths: "500 mg/vial (As Lyophilized)",
  },
  {
    productName: "Ganciclovir For Injection USP",
    strengths: "250 mg/vial (As Lyophilized)",
  },
  {
    productName: "Gemcitabine For Injection USP",
    strengths: "200 mg/vial (As Lyophilized)",
  },
  {
    productName: "Gemcitabine For Injection USP",
    strengths: "1000 mg/vial (As Lyophilized)",
  },
  {
    productName: "Gemcitabine For Injection USP",
    strengths: "1400 mg/vial (As Lyophilized)",
  },
  { productName: "Ibandronic Acid Injection", strengths: "1.0 mg/ml" },
  {
    productName: "Idarubicin Hydrochloride For Injection USP",
    strengths: "5.0 mg/vial (As Lyophilized)",
  },
  {
    productName: "Idarubicin Hydrochloride For Injection USP",
    strengths: "20 mg/vial (As Lyophilized)",
  },
  {
    productName: "Idarubicin Hydrochloride For Injection USP",
    strengths: "10 mg/vial (As Lyophilized)",
  },
  {
    productName: "Ifosfamide For Injection USP",
    strengths: "1.0 gm/vial (As Lyophilized)",
  },
  {
    productName: "Ifosfamide For Injection USP",
    strengths: "2.0 gm/vial (As Lyophilized)",
  },
  { productName: "Irinotecan Injection USP", strengths: "40 mg / 2.0 ml" },
  { productName: "Irinotecan Injection USP", strengths: "100 mg/5 ml" },
  {
    productName: "Ixabepilone For Injection",
    strengths: "15 mg (As Lyophilized)",
  },
  {
    productName: "Ixabepilone For Injection",
    strengths: "45 mg (As Lyophilized)",
  },
  {
    productName: "L-Asparaginase For Injection",
    strengths: "750 IU/ml (As Liposomal)",
  },
  {
    productName: "L-Asparaginase For Injection",
    strengths: "5000 IU/vial (As Lyophilized)",
  },
  {
    productName: "L-Asparaginase For Injection",
    strengths: "10,000 IU/vial (As Lyophilized)",
  },
  {
    productName: "Leucovorin Calcium Injection USP",
    strengths: "50 mg / 5 ml",
  },
  {
    productName: "Leuprolide Acetate For Injection",
    strengths: "3.75 mg (1 month depot) (As Lyophilized)",
  },
  {
    productName: "Leuprolide Acetate For Injection",
    strengths: "11.25 mg (3 month depot) (As Lyophilized)",
  },
  {
    productName: "Leuprolide Acetate For Injection",
    strengths: "22.5 mg (3 month depot) (As Lyophilized)",
  },
  {
    productName: "Melphalan For Injection BP",
    strengths: "50 mg/vial (As Lyophilized)",
  },
  { productName: "Mesna Injection", strengths: "100 mg/ml" },
  {
    productName: "Methotrexate For Injection USP",
    strengths: "250 mg/vial (As Lyophilized)",
  },
  {
    productName: "Methotrexate For Injection USP",
    strengths: "500 mg/vial (As Lyophilized)",
  },
  {
    productName: "Methotrexate For Injection USP",
    strengths: "50 mg/vial (As Lyophilized)",
  },
  { productName: "Methotrexate Injection BP", strengths: "5.0 gm/50 ml" },
  { productName: "Methotrexate Injection BP", strengths: "50 mg/2 ml" },
  { productName: "Methotrexate Injection BP", strengths: "500 mg/20 ml" },
  { productName: "Methotrexate Injection BP", strengths: "1000 mg/40 ml" },
  {
    productName: "Mitomycin For Injection USP",
    strengths: "10 mg/vial (As Lyophilized)",
  },
  {
    productName: "Mitomycin For Injection USP",
    strengths: "5.0 mg/vial (As Lyophilized)",
  },
  {
    productName: "Mitomycin For Injection USP",
    strengths: "20 mg/vial (As Lyophilized)",
  },
  {
    productName: "Mitomycin For Injection USP",
    strengths: "40 mg/vial (As Lyophilized)",
  },
  { productName: "Mitoxantrone Injection USP", strengths: "20 mg / 10 ml" },
  {
    productName: "Octreotide Acetate Injection",
    strengths: "1000 mcg/5 ml (0.2 mg/ml)",
  },
  {
    productName: "Oxaliplatin For Injection USP",
    strengths: "50 mg/vial (As Lyophilized)",
  },
  {
    productName: "Oxaliplatin For Injection USP",
    strengths: "100 mg/vial (As Lyophilized)",
  },
  { productName: "Oxaliplatin Injection USP", strengths: "50 mg/25 ml" },
  { productName: "Oxaliplatin Injection USP", strengths: "100 mg/50 ml" },
  {
    productName: "Paclitaxel (Protein Bound Particle) For Injection Suspension",
    strengths: "100 mg / vial",
  },
  { productName: "Paclitaxel Injection USP", strengths: "100/16.7 ml" },
  { productName: "Paclitaxel Injection USP", strengths: "30 mg/5 ml" },
  { productName: "Paclitaxel Injection USP", strengths: "260/43.4 ml" },
  { productName: "Paclitaxel Injection USP", strengths: "300/50 ml" },
  {
    productName: "Pamidronate Disodium For Injection USP",
    strengths: "30 mg/vial (As Lyophilized)",
  },
  {
    productName: "Pamidronate Disodium For Injection USP",
    strengths: "60 mg/vial (As Lyophilized)",
  },
  {
    productName: "Pamidronate Disodium For Injection USP",
    strengths: "90 mg/vial (As Lyophilized)",
  },
  {
    productName: "Pemetrexed For Injection USP",
    strengths: "100 mg/vial (As Lyophilized)",
  },
  {
    productName: "Pemetrexed For Injection USP",
    strengths: "500 mg/vial (As Lyophilized)",
  },
  { productName: "Tacrolimus Injection", strengths: "5 mg/ml" },
  { productName: "Temoporfin Injection", strengths: "2.0 mg/ml" },
  {
    productName: "Topotecan Hydrochloride For Injection",
    strengths: "4 mg (As Lyophilized)",
  },
  { productName: "Topotecan Injection", strengths: "2.5 mg" },
  { productName: "Treosulfan For Injection", strengths: "1.0 gm" },
  { productName: "Treosulfan For Injection", strengths: "5.0 gm" },
  {
    productName: "Triptorelin For Injection",
    strengths: "3.75 mg (As Lyophilized)",
  },
  {
    productName: "Triptorelin For Injection",
    strengths: "11.25 mg (As Lyophilized)",
  },
  {
    productName: "Triptorelin For Injection",
    strengths: "22.5 mg (As Lyophilized)",
  },
  { productName: "Vincristine Sulfate Injection USP", strengths: "1.0 mg/ml" },
  { productName: "Vinorelbine Injection USP", strengths: "10 mg/ml" },
  { productName: "Vinorelbine Injection USP", strengths: "50 mg/5 ml" },
  {
    productName: "Zoledronic Acid For Injection",
    strengths: "4.0 mg/vial (As Lyophilized)",
  },
];
