const oncologyData = [
  { productName: "Capecitabine Tablets USP 150/500 mg" },
  { productName: "Gefitinib Tablets 250 mg" },
  { productName: "Erlotinib Tablets 100/150 mg" },
  { productName: "Anastrozole Tablets 1.0 mg" },
  { productName: "Imatinib Tablets 100/400 mg" },
  { productName: "Methotrexate Tablets BP 2.5/7.5/15 mg" },
  { productName: "Everolimus Tablets 5.0/10 mg" },
  { productName: "Abiraterone Acetate Tablets USP 250/500 mg" },
  { productName: "Lapatinib Tablets 250 mg" },
  { productName: "Sorafenib Tablets 250 mg" },
  { productName: "Letrozole Tablets USP 2.5 mg" },
  { productName: "Tamoxifen Tablets BP 10/20/40 mg" },
  { productName: "Mercaptopurine Tablets BP 50 mg" },
  { productName: "Dasatinib Tablets 50/70/100 mg" },
  { productName: "Nilutamide Tablets 150 mg" },
  { productName: "Letrozole Tablet USP 2.5 mg" },
  { productName: "Flutamide Tablet 250 mg" },
  { productName: "Exemestane Tablet 25 mg" },
  { productName: "Fludarabine Phosphate Tablet 10 mg" },
  { productName: "Melphalan Tablets BP 2.0/4.0 mg" },
  { productName: "Mitotane Tablet USP 500 mg" },
  { productName: "Megestrol Acetate Tablet USP 40 mg/160 mg" },
  { productName: "Axitinib Tablet 1.0 mg, 5.0 mg" },
  { productName: "Pazopanib Tablet 200 mg, 400 mg" },
  { productName: "Valganciclovir Tablets USP 450" },
  { productName: "Deferasirox Tablets 125 mg , 250 mg, 500 mg" },
  { productName: "Regorafenib Tablets 40 mg" },
  { productName: "Osimertinib Tablets 40 mg, 80 mg" },
  { productName: "Mycophenolate Mofetil Tablets USP 500 mg" },
  { productName: "Etoposide Capsules USP 50/100 mg" },
  { productName: "Thalidomide  Capsules USP 50/100/200 mg" },
  { productName: "Temozolomide Capsules 5.0/20/100/250 mg" },
  { productName: "Imatinib Capsules 100 mg" },
  { productName: "Lenalidomide Capsules 5.0/10/15/25 mg" },
  { productName: "Sunitinib  Malate Capsules 12.5/25/50 mg" },
  { productName: "Ganciclovir Capsules  USP 250/500 mg" },
  { productName: "Crizotinib Capsules 200/250 mg" },
  { productName: "Tacrolimus Capsules USP 0.5/1.0 mg" },
  { productName: "Nilotinib Capsules 200 mg" },
  { productName: "Palbociclib Capsules 75/100/125 mg" },
  { productName: "Aprepitant Capsules BP 80/125 mg" },
  { productName: "Ibrutinib Capsules 140 mg" },
  { productName: "Hydroxyurea Capsules USP 500 mg" },
  { productName: "Procarbazine Hydrochloride Capsules USP 50 mg" },
  { productName: "Enzalutamide Capsules 40 mg" },
  { productName: "Danazol Capsules USP 200 mg" },
  { productName: "Tretinoin Capsules 10 mg" },
  { productName: "Lenvatinib Capsules 4.0 mg, 10 mg" },
  { productName: "Busulfan Injection 60 mg/10 ml" },
  {
    productName:
      "Paclitaxel Injection USP 30 mg/5ml/100/16.7ml/260/43.4ml/300/50ml",
  },
  {
    productName: "Cytarabine Injection BP 100 mg/ml, 500 mg/5ml, 1000 mg/10 ml",
  },
  {
    productName: "Docetaxel Injection USP20mg/0.5ml/80mg/2.0 ml/120 mg/3.0 ml",
  },
  { productName: "Oxaliplatin Injection USP 50 mg/25 ml/100 mg/50ml" },
  { productName: "Carboplatin Injection BP 150 mg/15 ml/450mg/45ml" },
  { productName: "Cisplatin Injection BP10 mg/20 ml/10mg/10ml/50mg/50ml" },
  {
    productName:
      "Etoposide Injection USP100 mg/5 ml, 250 mg/12.5ml, 500mg/25ml, 1000mg/50ml",
  },
  { productName: "Leucovorin Calcium Injection USP 50 mg / 5 ml" },
  { productName: "Epirubicin Injection BP 10 mg/5 ml/50mg/25ml" },
  { productName: "Doxorubicin Injection BP 10 mg/5ml/50mg/25ml" },
  { productName: "Vinorelbine Injection USP 10 mg/ml/50mg/5ml" },
  { productName: "Fluorouracil Injection BP 250 mg/10 ml/5ml" },
  { productName: "Irinotecan Injection USP 40 mg /2.0 ml/100mg/5ml" },
  { productName: "Mitoxantrone Injection USP 20 mg / 10 ml" },
  { productName: "Fulvestrant Injection 250 mg/ 5 ml" },
  { productName: "Eribulin Mesylate Solution For Injection 0.88mg/2 ml" },
  { productName: "Cabazitaxel Injection 60 mg/1.5 ml" },
  { productName: "Diluent For Cabazitaxel Injection 60 mg/1.5 ml" },
  { productName: "Temoporfin Injection 2.0 mg/ml" },
  { productName: "Ibandronic Acid Injection 1.0 mg/ml" },
  {
    productName:
      "Methotrexate Injection BP  50 mg/ 2 ml, 500mg/20ml, 1000mg/40ml, 5.0 gm/50ml",
  },
  { productName: "Mesna Injection 100 mg/ml" },
  { productName: "Daunorubicin Injection 50 mg/25 ml (As Liposomal)" },
  { productName: "L-Asparaginase For Injection 750 IU/ ml (As Liposomal)" },
  { productName: "Doxorubicin Injection 20 mg/10 ml (As Liposomal)" },
  { productName: "Cytarabine Injection 5.0 mg/ml (As Liposomal)" },
  { productName: "Pegaspargase For Injection 3750 IU/ 5ml (As Liposomal)" },
  { productName: "Fluorouracil Injection BP 50 mg/5 ml (As Liposomal)" },
  { productName: "Methotrexate Injection BP 100 mg/ml (As Liposomal)" },
  { productName: "Mesna Injection 50 mg/ml (As Liposomal)" },
  { productName: "Mitoxantrone Injection 2 mg/ml (As Liposomal)" },
  { productName: "Fulvestrant Injection 100 mg/ml (As Liposomal)" },
  { productName: "Eribulin Injection 10 mg/ml (As Liposomal)" },
  { productName: "Cabazitaxel Injection 30 mg/ml (As Liposomal)" },
  { productName: "Docetaxel Injection 20 mg/ml (As Liposomal)" },
  { productName: "Paclitaxel Injection 30 mg/ml (As Liposomal)" },
  { productName: "Bortezomib Injection 3.5 mg/vial" },
  { productName: "Bortezomib Injection 2 mg/vial" },
  { productName: "Cytarabine Injection BP 50 mg/ml (As Liposomal)" },
  { productName: "Paclitaxel Injection 150 mg/ml (As Liposomal)" },
  { productName: "Docetaxel Injection 100 mg/ml (As Liposomal)" },
  { productName: "Capecitabine Injection 100 mg/ml (As Liposomal)" },
  { productName: "Vincristine Sulfate Injection 1.0 mg/ml (As Liposomal)" },
  { productName: "Cyclophosphamide Injection 20 mg/ml (As Liposomal)" },
  { productName: "Doxorubicin Injection BP 20 mg/ml (As Liposomal)" },
  { productName: "Cytarabine Injection BP 20 mg/ml (As Liposomal)" },
  { productName: "Fluorouracil Injection BP 250 mg/ml (As Liposomal)" },
  { productName: "Bortezomib Injection 1 mg/vial" },
  { productName: "Methotrexate Injection BP 20 mg/ml (As Liposomal)" },
  { productName: "Mesna Injection BP 20 mg/ml (As Liposomal)" },
  { productName: "Epirubicin Injection BP 20 mg/ml (As Liposomal)" },
  { productName: "Bortezomib Injection 5 mg/vial" },
  { productName: "Oxaliplatin Injection BP 20 mg/ml (As Liposomal)" },
  { productName: "Carboplatin Injection BP 10 mg/ml (As Liposomal)" },
  { productName: "Cisplatin Injection BP 1.0 mg/ml (As Liposomal)" },
  { productName: "Etoposide Injection BP 2.0 mg/ml (As Liposomal)" },
  { productName: "Leucovorin Calcium Injection BP 10 mg/ml (As Liposomal)" },
  { productName: "Epirubicin Injection BP 5.0 mg/ml (As Liposomal)" },
  { productName: "Vinorelbine Injection BP 10 mg/ml (As Liposomal)" },
  { productName: "Fluorouracil Injection BP 5.0 mg/ml (As Liposomal)" },
  { productName: "Irinotecan Injection BP 10 mg/ml (As Liposomal)" },
  { productName: "Mitoxantrone Injection BP 2.0 mg/ml (As Liposomal)" },
  { productName: "Fulvestrant Injection BP 100 mg/ml (As Liposomal)" },
  { productName: "Eribulin Injection BP 10 mg/ml (As Liposomal)" },
  { productName: "Cabazitaxel Injection BP 30 mg/ml (As Liposomal)" },
  { productName: "Docetaxel Injection BP 100 mg/ml (As Liposomal)" },
  { productName: "Paclitaxel Injection BP 30 mg/ml (As Liposomal)" },
  { productName: "Capecitabine Injection BP 100 mg/ml (As Liposomal)" },
  { productName: "Vincristine Injection BP 1.0 mg/ml (As Liposomal)" },
  { productName: "Cyclophosphamide Injection BP 20 mg/ml (As Liposomal)" },
  { productName: "Doxorubicin Injection BP 20 mg/ml (As Liposomal)" },
  { productName: "Paclitaxel Injection BP 150 mg/ml (As Liposomal)" },
  { productName: "Docetaxel Injection BP 20 mg/ml (As Liposomal)" },
  { productName: "Fluorouracil Injection BP 20 mg/ml (As Liposomal)" },
  { productName: "Methotrexate Injection BP 50 mg/ml (As Liposomal)" },
  { productName: "Mesna Injection BP 50 mg/ml (As Liposomal)" },
  { productName: "Epirubicin Injection BP 10 mg/ml (As Liposomal)" },
  { productName: "Oxaliplatin Injection BP 100 mg/ml (As Liposomal)" },
  { productName: "Carboplatin Injection BP 20 mg/ml (As Liposomal)" },
  { productName: "Cisplatin Injection BP 20 mg/ml (As Liposomal)" },
  { productName: "Leucovorin Calcium Injection BP 100 mg/ml (As Liposomal)" },
  { productName: "Vinorelbine Injection BP 20 mg/ml (As Liposomal)" },
  { productName: "Fluorouracil Injection BP 50 mg/ml (As Liposomal)" },
  { productName: "Irinotecan Injection BP 20 mg/ml (As Liposomal)" },
  { productName: "Mitoxantrone Injection BP 20 mg/ml (As Liposomal)" },
  { productName: "Fulvestrant Injection BP 250 mg/ml (As Liposomal)" },
  { productName: "Eribulin Injection BP 20 mg/ml (As Liposomal)" },
  { productName: "Cabazitaxel Injection BP 60 mg/ml (As Liposomal)" },
];

export default oncologyData;
