const productData = {
  exports: [
    {
      label: "Injections",
      path: "/products/exports/injections",
      products: [
        {
          name: "Ceftriaxone",
          strengths: ["250mg", "500mg", "1000mg", "2000mg"],
        },
        {
          name: "Cefoperazon",
          strengths: ["250mg", "500mg", "1000mg", "2000mg"],
        },
        {
          name: "Ceftriaxone + Sulbactam",
          strengths: ["1000mg + 500mg", "2000mg + 1000mg"],
        },
        {
          name: "Ceftriaxone + Tazobactam",
          strengths: ["500mg + 62.5mg", "1000mg + 125mg", "2000mg + 250mg"],
        },
        {
          name: "Cefoperazone + Sulbactam",
          strengths: ["500mg + 500mg", "1000mg + 500mg", "1000mg + 1000mg"],
        },
        {
          name: "Ceftazidime",
          strengths: ["250mg", "500mg", "1000mg", "2000mg"],
        },
        {
          name: "Ceftazidime + Sulbactam",
          strengths: ["500mg + 250mg", "500mg + 500mg"],
        },
        { name: "Ceftazidime + Tobramycin", strengths: ["500mg + 60mg"] },
        {
          name: "Ceftazidime + Tazobactam",
          strengths: ["500mg + 62.5mg", "1000mg + 125mg"],
        },
        { name: "Ceftiofur Sodium", strengths: ["500mg", "1000mg"] },
        { name: "Cefepime", strengths: ["250mg", "500mg", "1000mg", "2000mg"] },
        {
          name: "Cefepime + Tazobactam",
          strengths: ["500mg + 62.5mg", "1000mg + 125mg"],
        },
        {
          name: "Cefuroxime",
          strengths: ["250mg", "500mg", "750mg", "1500mg"],
        },
        {
          name: "Cefuroxime + Sulbactam",
          strengths: ["750mg + 375mg", "1500mg + 750mg"],
        },
        { name: "Cefazolin", strengths: ["125mg", "250mg", "500mg", "1000mg"] },
        {
          name: "Amoxycillin + Clavulanic Acid",
          strengths: ["500mg + 100mg", "1000mg + 200mg"],
        },
        {
          name: "Amoxycillin + Cloxacillin",
          strengths: ["1.75mg + 1.75mg", "2000mg + 2000mg"],
        },
        { name: "Amoxycillin + Sulbactam", strengths: ["2000mg + 1000mg"] },
        { name: "Amoxycillin + Dicloxacillin", strengths: ["2000mg + 2000mg"] },
        {
          name: "Imipenem + Cilastatin",
          strengths: ["500mg + 500mg", "250mg + 250mg", "1000mg + 1000mg"],
        },
        {
          name: "Ampicillin",
          strengths: ["100mg", "250mg", "500mg", "1000mg"],
        },
        {
          name: "Ampicillin + Sulbactam",
          strengths: ["500mg + 250mg", "2000mg + 1000mg", "1000mg + 500mg"],
        },
        {
          name: "Enoxaparin injection PFS",
          strengths: ["40mg./0.4ml", "60mg./0.6ml"],
        },
        { name: "Nandrolone Decanoate", strengths: ["200mg", "250mg"] },
        { name: "Nandrolone Propionate", strengths: ["250mg"] },
        { name: "Carboprost Tromethamine", strengths: ["250mcg"] },
        {
          name: "Progesterone + Ethinylestradiol",
          strengths: ["12.5mg + 0.02mg"],
        },
        { name: "Hydroxyprogesterone Caproate", strengths: ["250mg", "500mg"] },
        { name: "Amikacin", strengths: ["500mg"] },
        { name: "Pantoprazole", strengths: ["40mg"] },
        { name: "Omeprazole", strengths: ["40mg"] },
        { name: "Esomeprazole", strengths: ["40mg"] },
        { name: "Rabeprazole", strengths: ["20mg"] },
        { name: "Lignocaine Hydrochloride", strengths: ["20mg"] },
        {
          name: "Lignocaine Hydrochloride + Adrenaline Bitartrates",
          strengths: ["20mg + 1.01mg"],
        },
        { name: "Hydralazine Hydrochloride", strengths: ["20mg"] },
        { name: "Triamcinolone Acetonide", strengths: ["40mg"] },
        { name: "Hyoscine Butylbromide", strengths: ["10mg"] },
        { name: "Clindamycin", strengths: ["300mg"] },
        { name: "Hydrocortisone Sodium Succinate", strengths: ["100mg"] },
        { name: "Iron Sucrose", strengths: ["50mg", "100mg", "200mg"] },
        { name: "Acyclovir Sodium", strengths: ["250mg", "500mg", "1000mg"] },
        { name: "Vancomycin", strengths: ["500mg", "1000mg"] },
        { name: "Methylpredlisone Acetate", strengths: ["40mg"] },
        {
          name: "Methylprednisolone Sodium Succinate",
          strengths: ["125mg", "500mg", "1000mg"],
        },
        { name: "Chloramphenicol Sodium Succinate", strengths: ["1000mg"] },
        {
          name: "Streptomycin Sulphate",
          strengths: ["500mg", "1000mg", "5000mg"],
        },
        {
          name: "Artesunate",
          strengths: ["30mg", "60mg", "120mg", "180mg", "240mg"],
        },
        { name: "Dexamethasone Sodium Phosphate", strengths: ["1ml", "2ml"] },
        { name: "Betamethasone", strengths: ["1ml", "2ml"] },
        {
          name: "Heparin Sodium",
          strengths: [
            "5000 iu/5ml",
            "10000 iu/5ml",
            "25000 iu/5ml",
            "50000 iu/5ml",
          ],
        },
        {
          name: "B-Complex",
          strengths: ["1ml", "2ml", "3ml Amp.", "10ml Vial"],
        },
        { name: "Fluphenazine Decanoate", strengths: ["25mg/ml"] },
        { name: "Tigecycline", strengths: ["50mg", "100mg"] },
        { name: "Teicoplanin", strengths: ["200mg", "400mg"] },
        { name: "Aztreonam USP", strengths: ["1000mg"] },
        { name: "Meropenem", strengths: ["500mg", "1000mg"] },
        { name: "Cisatracurium Besylate", strengths: ["2mg"] },
        { name: "Testosterone Deconate", strengths: ["100mg"] },
        { name: "Testosterone Isocaproate", strengths: ["100mg"] },
        { name: "Fondaparinum Sodium Sterile USP", strengths: ["2.5mg"] },
        { name: "Glutathione", strengths: ["600 mg"] },
        { name: "Caspofungin Acetate", strengths: ["50mg"] },
        { name: "Arthemether", strengths: ["80mg"] },
        { name: "Ganciclovir", strengths: ["500mg"] },
      ],
    },
    {
      label: "Oral Solids",
      path: "/products/exports/oral-solids",
      subcategories: [
        {
          label: "Tablets",
          path: "/products/exports/oral-solids/tablets",
          products: [
            {
              serialNo: 1,
              productName: "ACECLOFENAC TABLETS",
              strengths: ["100mg"],
              coating: "FC",
            },
            {
              serialNo: 2,
              productName: "ACECLOFENAC (SR) TABLETS",
              strengths: ["200mg"],
              coating: "FC",
            },
            {
              serialNo: 3,
              productName: "ACECLOFENAC + PARACETAMOL TABLETS",
              strengths: ["100mg + 325mg"],
              coating: "FC",
            },
            {
              serialNo: 4,
              productName: "ACICLOVIR TABLETS BP",
              strengths: ["200mg", "400mg"],
              coating: "UC",
            },
            {
              serialNo: 5,
              productName: "ALBENDAZOLE TABLETS (CHEWABLE)",
              strengths: ["400mg"],
              coating: "UC",
            },
            {
              serialNo: 6,
              productName: "AMLODIPINE BESYLATE TABLETS USP",
              strengths: ["2.5mg", "5mg", "10mg"],
              coating: "UC",
            },
            {
              serialNo: 7,
              productName: "AMLODIPINE + ATENOLOL TABLETS",
              strengths: ["5mg + 5mg"],
              coating: "UC",
            },
            {
              serialNo: 8,
              productName: "ASCORBIC ACID TABLETS BP",
              strengths: ["100mg", "250mg"],
              coating: "UC",
            },
            {
              serialNo: 9,
              productName: "ASPIRIN TABLETS BP",
              strengths: ["75mg", "100mg", "300mg", "500mg"],
              coating: "EC/UC",
            },
            {
              serialNo: 10,
              productName: "ATORVASTATIN TABLETS",
              strengths: ["5mg", "10mg", "20mg", "40mg", "80mg"],
              coating: "FC",
            },
            {
              serialNo: 11,
              productName: "AZITHROMYCIN TABLETS USP",
              strengths: ["250mg", "500mg"],
              coating: "FC",
            },
            {
              serialNo: 12,
              productName: "BISOPROLOL FUMARATE TABLETS USP",
              strengths: ["2.5mg", "5mg"],
              coating: "FC",
            },
            {
              serialNo: 13,
              productName: "CALCIUM CARBONATE + VITAMIN D3 TABLETS",
              strengths: [
                "250mg (625mg) / 500mg / 1250mg + 250IU/500IU/1000IU",
              ],
              coating: "FC",
            },
            {
              serialNo: 14,
              productName:
                "CALCIUM CITRATE + MAGNESIUM HYDROXIDE + ZINC SULPHATE + VITAMIN D3 TABLETS",
              strengths: ["1000mg + 20mg + 11mg + 250IU"],
              coating: "UC",
            },
            {
              serialNo: 15,
              productName:
                "CALCIUM CITRATE + MAGNESIUM HYDROXIDE + ZINC SULPHATE + VITAMIN D3 TABLETS",
              strengths: ["1000mg(211) + 260 (90mg) + 4mg + 1000IU"],
              coating: "UC",
            },
            {
              serialNo: 16,
              productName: "CAPTOPRIL TABLETS BP",
              strengths: ["25mg", "50mg"],
              coating: "UC",
            },
            {
              serialNo: 17,
              productName: "CARBIDOPA + LEVODOPA + ENTACAPONE TABLETS",
              strengths: ["25mg + 100mg + 200mg"],
              coating: "FC",
            },
            {
              serialNo: 18,
              productName: "CARVIDILOL TABLETS",
              strengths: ["3.125mg", "6.5mg", "12.5mg", "25mg"],
              coating: "UC",
            },
            {
              serialNo: 19,
              productName: "CETRIZINE TABLETS BP/USP",
              strengths: ["10mg"],
              coating: "UC/FC",
            },
            {
              serialNo: 20,
              productName: "CHLORTHALIDONE TABLETS BP",
              strengths: ["6.25mg", "12.5mg"],
              coating: "FC",
            },
            {
              serialNo: 21,
              productName: "CIPROFLOXACIN TABLETS BP",
              strengths: ["250mg", "500mg"],
              coating: "FC",
            },
            {
              serialNo: 22,
              productName: "CITICOLINE TABLETS",
              strengths: ["500mg"],
              coating: "FC",
            },
            {
              serialNo: 23,
              productName: "CLARITHROMYCIN TABLETS",
              strengths: ["250mg", "500mg"],
              coating: "FC",
            },
            {
              serialNo: 24,
              productName: "CLOPIDOGREL TABLETS USP",
              strengths: ["75mg"],
              coating: "FC/UC",
            },
            {
              serialNo: 25,
              productName: "CLOTRIMAZOLE PESSARIES BP",
              strengths: ["100mg", "500mg"],
              coating: "UC",
            },
            {
              serialNo: 26,
              productName: "DESLORATADINE TABLETS USP",
              strengths: ["5mg", "25mg"],
              coating: "FC",
            },
            {
              serialNo: 27,
              productName: "DEXKETOPROFEN + PARACETAMOL TABLETS",
              strengths: ["25mg + 325mg"],
              coating: "FC",
            },
            {
              serialNo: 28,
              productName: "DICLOFENAC POTASSIUM + PARACETAMOL TABLETS",
              strengths: ["50mg + 325mg"],
              coating: "FC",
            },
            {
              serialNo: 29,
              productName: "DICLOFENAC POTASSIUM + SERRATIOPEPTIDASE TABLETS",
              strengths: ["50mg + 10mg"],
              coating: "EC",
            },
            {
              serialNo: 30,
              productName: "DICYCLOMINE HCL. + PARACETAMOL TABLETS",
              strengths: ["20mg + 325mg"],
              coating: "UC",
            },
            {
              serialNo: 31,
              productName: "DICYCLOVERINE TABLETS BP",
              strengths: ["10mg"],
              coating: "UC",
            },
            {
              serialNo: 32,
              productName: "DOMPERIDONE TABLETS BP",
              strengths: ["10mg"],
              coating: "UC",
            },
            {
              serialNo: 33,
              productName: "DONEPEZIL HCL TABLETS",
              strengths: ["5mg", "10mg"],
              coating: "FC",
            },
            {
              serialNo: 34,
              productName: "DOXYCYCLINE HYCLATE TABLETS USP",
              strengths: ["100mg"],
              coating: "FC",
            },
            {
              serialNo: 35,
              productName: "DROTAVERIN HCL. TABLETS",
              strengths: ["80mg"],
              coating: "FC",
            },
            {
              serialNo: 36,
              productName: "DROTAVERINE HCL. + MEFENAMIC ACID TABLETS",
              strengths: ["80mg + 250mg"],
              coating: "FC",
            },
            {
              serialNo: 37,
              productName: "ENALAPRIL MALEATE TABLETS",
              strengths: ["2.5mg", "5mg", "10mg"],
              coating: "UC",
            },
            {
              serialNo: 38,
              productName: "ENAPRIL MALEATE + HYDROCHLORTHIAZIDE TABLETS",
              strengths: ["10mg + 25mg"],
              coating: "FC",
            },
            {
              serialNo: 39,
              productName: "ERYTHROMYCIN STREATE TABLETS BP",
              strengths: ["250mg", "500mg"],
              coating: "FC",
            },
            {
              serialNo: 40,
              productName: "ESCITALOPRAM OXALATE TABLETS",
              strengths: ["5mg", "10mg", "20mg"],
              coating: "FC",
            },
            {
              serialNo: 41,
              productName: "ESOMEPRAZOLE TABLETS",
              strengths: ["20mg", "40mg"],
              coating: "FC",
            },
            {
              serialNo: 42,
              productName: "ETODOLAC EXTENDED RELEASE TABLETS",
              strengths: ["600mg"],
              coating: "FC",
            },
            {
              serialNo: 43,
              productName: "ETORICOXIB TABLETS",
              strengths: ["90mg", "120mg"],
              coating: "FC",
            },
            {
              serialNo: 44,
              productName: "FENOFIBRATE TABLETS USP",
              strengths: ["145mg", "160mg", "200mg"],
              coating: "FC",
            },
            {
              serialNo: 45,
              productName: "FEXOFENADINE HCL. TABLETS",
              strengths: ["120mg", "180mg"],
              coating: "FC",
            },
            {
              serialNo: 46,
              productName: "FLUCONAZOLE TABLETS USP",
              strengths: ["150mg", "200mg"],
              coating: "UC",
            },
            {
              serialNo: 47,
              productName: "FOLIC ACID TABLETS BP",
              strengths: ["5mg"],
              coating: "UC",
            },
            {
              serialNo: 48,
              productName: "FRUSEMIDE TABLETS USP/BP",
              strengths: ["40mg"],
              coating: "UC",
            },
            {
              serialNo: 49,
              productName: "GABAPENTIN + MECOBALAMIN TABLETS",
              strengths: ["300mg + 500mcg"],
              coating: "FC",
            },
            {
              serialNo: 50,
              productName: "GLICLAZIDE + METFORMIN HCL. TABLETS",
              strengths: ["40mg/80mg + 500mg"],
              coating: "UC/FC",
            },
            {
              serialNo: 51,
              productName: "GLUCOSAMINE TABLETS USP",
              strengths: ["500mg"],
              coating: "UC",
            },
            {
              serialNo: 52,
              productName:
                "GLUCOSAMINE SULPHATE POTASSIUM CHLORIDE + DIACERINE TABLETS",
              strengths: ["1500mcg + 50mg"],
              coating: "FC",
            },
            {
              serialNo: 53,
              productName: "IBUPROFEN TABLETS BP",
              strengths: ["200mg", "400mg"],
              coating: "FC",
            },
            {
              serialNo: 54,
              productName: "IVERMECTIN TABLETS USP",
              strengths: ["12mg"],
              coating: "UC",
            },
            {
              serialNo: 55,
              productName: "LAMOTRIGINE DISPERSIBLE TABLETS",
              strengths: ["25mg", "50mg"],
              coating: "UC",
            },
            {
              serialNo: 56,
              productName: "LEVETIRACETAM TABLETS",
              strengths: ["500mg"],
              coating: "FC",
            },
            {
              serialNo: 57,
              productName: "LEVOCETRIZINE HCL. TABLETS",
              strengths: ["5mg"],
              coating: "FC",
            },
            {
              serialNo: 58,
              productName: "LEVOFLOXACIN TABLETS USP",
              strengths: ["250mg", "500mg", "750mg"],
              coating: "SC/FC",
            },
            {
              serialNo: 59,
              productName: "LISINOPRIL TABLETS BP",
              strengths: ["2.5mg", "5mg", "10mg", "20mg"],
              coating: "UC",
            },
            {
              serialNo: 60,
              productName: "LISINOPRIL + AMLODIPINE BESYLATE TABLETS",
              strengths: ["5mg + 5mg"],
              coating: "UC",
            },
            {
              serialNo: 61,
              productName: "LORATADINE TABLETS BP",
              strengths: ["10mg"],
              coating: "UC",
            },
            {
              serialNo: 62,
              productName: "LOSARTAN POTTASIUM TABLETS",
              strengths: ["25mg", "50mg", "100mg"],
              coating: "FC",
            },
            {
              serialNo: 63,
              productName:
                "LOSARTAN POTTASIUM + HYDROCHLORTHIAZIDE TABLETS USP",
              strengths: ["50mg + 12.5mg"],
              coating: "FC",
            },
            {
              serialNo: 64,
              productName: "MEBENDAZOLE TABLETS USP",
              strengths: ["100mg"],
              coating: "UC",
            },
            {
              serialNo: 65,
              productName: "MELOXICAM TABLETS BP",
              strengths: ["7.5mg", "15mg"],
              coating: "UC",
            },
            {
              serialNo: 66,
              productName: "MEMANTINE HCL. TABLETS",
              strengths: ["5mg", "10mg"],
              coating: "FC",
            },
            {
              serialNo: 67,
              productName: "MESALAMINE DELAYED RELEASE TABLETS USP",
              strengths: ["400mg", "500mg", "1200mg"],
              coating: "EC",
            },
            {
              serialNo: 68,
              productName: "METFORMIN TABLETS BP",
              strengths: ["500mg", "850mg", "1000mg"],
              coating: "UC/FC/SR",
            },
            {
              serialNo: 69,
              productName: "METOPROLOL SUCCINATE (SR) TABLETS",
              strengths: ["12.5mg", "25mg", "50mg"],
              coating: "FC",
            },
            {
              serialNo: 70,
              productName: "METRONIDAZOLE VAGINAL TABLETS USP",
              strengths: ["500mg"],
              coating: "UC",
            },
            {
              serialNo: 71,
              productName: "MONTELUKAST SODIUM TABLETS",
              strengths: ["5mg", "10mg"],
              coating: "UC",
            },
            {
              serialNo: 72,
              productName: "MONTELUKAST SODIUM + LEVOCETRIZINE HCL. TABLETS",
              strengths: ["10mg + 5mg"],
              coating: "FC",
            },
            {
              serialNo: 73,
              productName: "MONTELUKAST SODIUM MOUTH DISSOLVING TABLETS",
              strengths: ["5mg"],
              coating: "UC",
            },
            {
              serialNo: 74,
              productName: "MOXIFLOXACIN HCL. TABLETS",
              strengths: ["400mg"],
              coating: "FC",
            },
            {
              serialNo: 75,
              productName: "NIFEDIPINE TABLETS",
              strengths: ["20mg"],
              coating: "FC",
            },
            {
              serialNo: 76,
              productName: "NIFEDIPINE SUSTAINED RELEASE TABLETS",
              strengths: ["5mg", "10mg"],
              coating: "FC",
            },
            {
              serialNo: 77,
              productName: "NORFLOXACIN TABLETS BP",
              strengths: ["400mg"],
              coating: "FC",
            },
            {
              serialNo: 78,
              productName: "OFLOXACIN TABLETS BP",
              strengths: ["200mg"],
              coating: "FC",
            },
            {
              serialNo: 79,
              productName: "OFLOXACIN + ORNIDAZOLE TABLETS",
              strengths: ["200mg + 500mg"],
              coating: "FC",
            },
            {
              serialNo: 80,
              productName: "OLMESARTAN MEDOXOMIL TABLETS",
              strengths: ["10mg", "20mg", "40mg"],
              coating: "FC",
            },
            {
              serialNo: 81,
              productName: "PANTOPRAZOLE DELAYED RELEASE TABLETS USP",
              strengths: ["20mg", "40mg"],
              coating: "EC",
            },
            {
              serialNo: 82,
              productName: "PANTOPRAZOLE + DOMPERIDONE TABLETS",
              strengths: ["40mg + 10mg"],
              coating: "EC",
            },
            {
              serialNo: 83,
              productName: "PARACETAMOL TABLETS BP",
              strengths: ["100mg", "250mg", "500mg", "650mg"],
              coating: "UC",
            },
            {
              serialNo: 84,
              productName:
                "PARACETAMOL + DIPHENHYDRAMINE HCL + PHENYLEPHERINE HCL + CAFFIENE TABLETS",
              strengths: ["500mg + 25mg + 5mg + 30mg"],
              coating: "UC",
            },
            {
              serialNo: 85,
              productName:
                "PARACETAMOL + PHENYLEPHRINE HCL. + LEVOCETRIZINE HCL. TABLETS",
              strengths: ["325mg/500mg + 10mg + 2.5mg"],
              coating: "UC",
            },
            {
              serialNo: 86,
              productName: "PARACETAMOL + PHENYLEPHRINE + CETRIZINE TABLETS",
              strengths: ["325mg/500mg + 10mg + 5mg"],
              coating: "UC",
            },
            {
              serialNo: 87,
              productName: "PROCHLORPERAZINE TABLETS BP",
              strengths: ["5mg"],
              coating: "UC",
            },
            {
              serialNo: 88,
              productName: "RABEPRAZOLE GASTRO RESISTANT TABLETS BP",
              strengths: ["20mg", "40mg"],
              coating: "EC",
            },
            {
              serialNo: 89,
              productName: "RABEPRAZOLE SODIUM + DOMPERIDONE TABLETS",
              strengths: ["20mg + 10mg"],
              coating: "EC",
            },
            {
              serialNo: 90,
              productName: "RIFAMPICIN + ISONIAZID TABLETS",
              strengths: ["600mg + 300mg"],
              coating: "FC",
            },
            {
              serialNo: 91,
              productName: "ROSUVASTATIN TABLETS",
              strengths: ["5mg", "10mg", "20mg", "40mg"],
              coating: "FC",
            },
            {
              serialNo: 92,
              productName: "SERTRALINE TABLETS BP",
              strengths: ["25mg", "50mg", "100mg"],
              coating: "FC",
            },
            {
              serialNo: 93,
              productName: "SILDENAFIL CITRATE TABLETS",
              strengths: ["25mg", "50mg", "100mg"],
              coating: "FC",
            },
            {
              serialNo: 94,
              productName: "SIMVASTATIN TABLETS USP",
              strengths: ["5mg", "10mg", "20mg", "40mg"],
              coating: "FC",
            },
            {
              serialNo: 95,
              productName: "TADALAFIL TABLETS USP",
              strengths: ["5mg", "20mg"],
              coating: "FC",
            },
            {
              serialNo: 96,
              productName: "TELMISARTAN TABLETS BP",
              strengths: ["20mg", "40mg", "80mg"],
              coating: "FC",
            },
            {
              serialNo: 97,
              productName: "TELMISARTAN + AMLODIPINE TABLETS",
              strengths: ["40mg/80mg + 5mg"],
              coating: "UC",
            },
            {
              serialNo: 98,
              productName: "TELMISARTAN + HYDROCHLORTHIAZIDE TABLETS",
              strengths: ["40mg + 12.5mg"],
              coating: "UC",
            },
            {
              serialNo: 99,
              productName: "URSODEOXYCHOLIC ACID TABLETS",
              strengths: ["300mg"],
              coating: "FC",
            },
          ],
        },
        { label: "Capsules", path: "/products/exports/oral-solids/capsules" },
      ],
    },
    { label: "Oral Liquids", path: "/products/exports/oral-liquids" },
    { label: "Infusions", path: "/products/exports/infusions" },
    { label: "Foot and OTC", path: "/products/exports/foot-and-otc" },
    { label: "Pediatric", path: "/products/exports/pediatric" },
  ],
  domestic: [
    { label: "Pediatrics", path: "/products/domestic/pediatrics" },
    { label: "General", path: "/products/domestic/general" },
  ],
};

export default productData;
